# Generated by Django 3.2 on 2023-02-04 14:35

import django.contrib.auth.validators
from django.db import migrations, models
import users.validators


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(db_index=True, max_length=150, unique=True, validators=[users.validators.username_validator, django.contrib.auth.validators.UnicodeUsernameValidator], verbose_name='Никнейм пользователя'),
        ),
    ]
