# Generated by Django 3.2 on 2023-01-29 09:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(db_index=True, max_length=150, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_username', message='Имя пользователя должно состоять только из букв латинского алфавита, цифр и символов "@/./+/-/_"', regex='^[\\w.@+-]+\\Z')], verbose_name='Никнейм пользователя'),
        ),
    ]
