# Generated by Django 3.2 on 2023-01-29 11:11

from django.db import migrations, models
import users.validators


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_remove_user_confirmation_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(db_index=True, max_length=150, unique=True, validators=[users.validators.username_validator], verbose_name='Никнейм пользователя'),
        ),
    ]
