# Generated by Django 3.2 on 2023-01-25 11:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Заполните имя категории', max_length=256, verbose_name='Название')),
                ('slug', models.SlugField(help_text='Поле с уникальным значением', unique=True)),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категория',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Genres',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Заполните имя жанра', max_length=256, verbose_name='Название')),
                ('slug', models.SlugField(help_text='Поле с уникальным значением', unique=True)),
            ],
            options={
                'verbose_name': 'Жанры',
                'verbose_name_plural': 'Жанры',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Titles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Заполните название произведения', max_length=256, verbose_name='Название')),
                ('year', models.IntegerField(help_text='Заполните год выпуска', verbose_name='Год выпуска')),
                ('description', models.TextField(blank=True, help_text='Заполните описание', null=True, verbose_name='описание')),
                ('category', models.ForeignKey(blank=True, help_text='Выберите категорию', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='titles', to='reviews.categories', verbose_name='категория')),
                ('genre', models.ManyToManyField(blank=True, help_text='Выберите один или несколько жанров', related_name='genre', to='reviews.Genres', verbose_name='жанр')),
            ],
            options={
                'verbose_name': 'Произведения',
                'verbose_name_plural': 'Произведения',
                'ordering': ('name',),
            },
        ),
    ]
