# Generated by Django 3.2 on 2023-02-04 16:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='score',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1, message='Убедитесь, что оценка не меньше 1.'), django.core.validators.MaxValueValidator(10, message='Убедитесь, что оценка не больше 10.')], verbose_name='Оценка'),
        ),
        migrations.AlterField(
            model_name='title',
            name='year',
            field=models.PositiveSmallIntegerField(help_text='Заполните год выпуска', verbose_name='Год выпуска'),
        ),
    ]
