# Generated by Django 3.2 on 2023-02-05 18:26

from django.db import migrations, models
import users.validators


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_auto_20230204_1619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='year',
            field=models.PositiveSmallIntegerField(help_text='Заполните год выпуска', validators=[users.validators.year_validator], verbose_name='Год выпуска'),
        ),
    ]
